
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

# Custom config
mqtt:
  broker: 127.0.0.1

recorder:
  db_url: postgresql://{{ POSTGRES_USER }}:{{ POSTGRES_PASSWORD }}@127.0.0.1/postgres

http:
  base_url: {{ FQSN }}
  use_x_forwarded_for: True
  trusted_proxies: 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 5

homeassistant:
  time_zone: {{ TZ }}
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
